name: json2yaml
description: Dart package to format JSON data to YAML. Supports formatting conventions of pubspec files.
version: 1.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  dependency_validator: ^3.1.0
  test: ^1.17.7
  ##test_coverage: ^0.5.0
  yaml: ^3.1.0
